const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCTSBYCATEGORY: '/products/category',
  CATEGORIES: '/categories',
  POSTS: '/posts',
  POSTSBYCATEGORY: '/posts/category',
  POSITIONS: '/positions',
  RECRUIT: '/recruit',
  RECRUITSUCCESS: '/recruit-success',
  ABOUT: '/about',
  CONTACT: '/contact',
  LOGIN: '/login',
  LOGOUT: '/logout',
  REGISTER: '/register',
  FORGOTPASSWORD: '/forgot-password',
  RESETPASSWORD: '/reset-password',
  ADMIN: '/admin/*',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PROFILE: '/profile',
  EDITPROFILE: '/profile-edit',
  PAYMENT: '/payment',
  ORDERS: '/my-orders',
  ORDERSUCCESS: '/order-success',
  ORDERDETAIL: '/order-detail',
  RATING: '/rating',
};

export default ROUTES;
